### PR TITLE
fix(rum-core): consider user defined type of high precedence

### LINKED ISSUE #758: React withTransaction not redefining transaction type
I'm using `withTransaction` from the react package, but its behaving strangely. I'm still getting `route-change` events, but not the custom `component` events that should be happening (I'm following the [elastic docs](https://www.elastic.co/guide/en/apm/agent/rum-js/5.x/react-integration.html#_instrumenting_individual_react_components) to create the custom `component` transactions). When I turn logging to debug, it says the transaction type is redefined at first, but it doesn't appear to stick once the transaction is actually done? The custom name does appear to stick

image

### PR DESCRIPTION
**Pull request by vigneshshanmugam**
+ fix #758 
+ User defined type for managed transaction should be considered a high priority as it would let users to filter these transactions in the UI in a better way. This applies only to managed transaction and custom transactions is not touched in this PR. 
+ Also moved and improved the logging after the redefining as it gives false information as mentioned in the linked issue.

### CODE REVIEW

**Comment by vigneshshanmugam** [comment]
@jahtalab Integration test failure is unrelated, Good to be reviewed.

File: packages/rum-core/src/performance-monitoring/transaction-service.js [hunk 1]
```diff
@@ -139,28 +139,36 @@ class TransactionService {
...
+        } else if (
+          /**
+           * Update type based on precedence defined in TRANSACTION_TYPE_ORDER.
+           * If either orders don't exist we also don't redefine the type.
+           */
+          redefineTypeOrder >= 0 &&
+          redefineTypeOrder < currentTypeOrder
+        ) {
+          redefineType = type
+        }
```
Comment (jahtalab) [inline packages/rum-core/src/performance-monitoring/transaction-service.js:162]: I think this if can be written as follows and it would have the same effect:

```suggestion
        if (redefineTypeOrder < currentTypeOrder) {
          redefineType = type
        }
```

Comment (vigneshshanmugam) [reply packages/rum-core/src/performance-monitoring/transaction-service.js:162]: try harding `if else` 😅

File: packages/rum-core/src/performance-monitoring/transaction-service.js [hunk 2]
```diff
@@ -139,28 +139,27 @@ class TransactionService {
...
+       */
+      if (currentTypeOrder >= 0 && redefineTypeOrder < currentTypeOrder) {
+        redefineType = type
+      }
       if (__DEV__) {
         this._logger.debug(
           `redefining transaction(${tr.id}, ${tr.name}, ${tr.type})`,
           'to',
-          `(${name}, ${type})`,
+          `(${name || tr.name}, ${redefineType})`,
```
Comment (vigneshshanmugam) [inline packages/rum-core/src/performance-monitoring/transaction-service.js:159]: sometimes, the name is undefined so it's better to log the redefined name without any changes.
