### PR TITLE
fix(rum-core): do not capture timing spans for unsampled transactions

### LINKED ISSUE #579: Avoid capturing multiple timings if the transaction is unsampled
We should not capture resource timing API, user timing, breakdown metrics if the transaction is upsampled

### PR DESCRIPTION
**Pull request by vigneshshanmugam**
+ fix #579

### CODE REVIEW

File: packages/rum-core/src/performance-monitoring/transaction-service.js [hunk 1]
```diff
@@ -175,6 +173,14 @@ class TransactionService {
       }
     }
 
+    /**
+     * For unsampled transactions, avoid capturing various timing informations
+     * as spans as they are dropped anyways before sending to the server
```
Comment (jahtalab) [inline packages/rum-core/src/performance-monitoring/transaction-service.js]: nit: you should use 'information' instead of 'informations',  also 'as they' is redundant.

File: packages/rum-core/test/performance-monitoring/transaction-service.spec.js [hunk 2]
```diff
@@ -170,6 +170,25 @@ describe('TransactionService', function() {
     tr2.detectFinish()
   })
 
+  it('should not capture timings as spans for unsampled transactions', done => {
+    const unMock = mockGetEntriesByType()
+
+    config.events.observe(TRANSACTION_END, () => {
```
Comment (jahtalab) [inline packages/rum-core/test/performance-monitoring/transaction-service.spec.js]: Should use the transaction that is passed to the event listener instead
