### PR TITLE
fix(rum): return noop agent when config is inactive

### LINKED ISSUE #210: active: false should be a noop during initialization phase
In RUM agent, when `active: false` is set in the config, 
+ We initialize the agent with active listeners on window.load, window.onerror and also patch fetch and XHR calls. 
+ The agent just dont send the transaction as well the erros captured during active: false. 

This is not the intended behaviour of active flag and it does not align with other agents. 

`active: false` would simply a noop in the agent which means we wont be patching any browser API's and also listening for events.

### PR DESCRIPTION
**Pull request by vigneshshanmugam**
+ fix elastic/apm-agent-rum-js#210 
+ Extracted from elastic/apm-agent-rum-js#216 
+ Refactored few methods to reduce the code size.

### CODE REVIEW

File: packages/rum-core/src/common/apm-server.js [hunk 1]
```diff
@@ -252,29 +226,47 @@ class ApmServer {
...
-            NDJSON.stringify({ metadata: { service: filteredPayload.service } })
-          )
-          const ndjsonPayload = ndjson.join('')
-          return this._postJson(endPoint, ndjsonPayload)
-        } else {
-          this._loggingService.warn('Dropped payload due to filtering!')
-        }
-      }
-    } else {
+  _send(data, type = 'transaction') {
```
Comment (jahtalab) [inline packages/rum-core/src/common/apm-server.js]: I don't think we should have a default value here, if `type` isn't provided we should either throw or return!

I think we should also check `data`!

File: packages/rum-core/src/common/config-service.js [hunk 2]
```diff
@@ -98,18 +104,17 @@ class Config {
 
       distributedTracing: true,
       distributedTracingOrigins: [],
-      distributedTracingHeaderValueCallback: undefined,
+      distributedTracingHeaderValueCallback: getDtHeaderValue,
```
Comment (jahtalab) [inline packages/rum-core/src/common/config-service.js]: I think we might remove this config option once our we transition to the w3c `traceparent` header.

File: packages/rum-core/src/common/config-service.js [hunk 3]
```diff
@@ -211,26 +213,16 @@ class Config {
...
-
-    setTag(key, value, this.config.context.tags)
-  }
-
-  addTags(tags) {
     var keys = Object.keys(tags)
-    keys.forEach(k => {
-      this.setTag(k, tags[k])
-    })
+    keys.map(k => setTag(k, tags[k], this.config.context.tags))
```
Comment (jahtalab) [inline packages/rum-core/src/common/config-service.js]: Did you mean to use `forEach` since you are not mapping the array to anything!

File: packages/rum/test/specs/apm-base.spec.js [hunk 4]
```diff
@@ -154,29 +179,6 @@ describe('ApmBase', function() {
     expect(tr.name).toBe('ZoneTransaction')
   })
 
-  it('should instrument xhr when not active', function(done) {
```
Comment (jahtalab) [inline packages/rum/test/specs/apm-base.spec.js]: We still instrument XHR even if not active! patching is called in the `bootstrap.js` file

File: packages/rum/test/specs/apm-base.spec.js [hunk 5]
```diff
@@ -67,6 +67,31 @@ describe('ApmBase', function() {
     })
   })
 
+  it('should be noop when agent is not active', done => {
```
Comment (jahtalab) [inline packages/rum/test/specs/apm-base.spec.js]: What will happen if users call `startTransaction` on an inactive agent. We should have a test for that as well.

File: packages/rum-core/src/common/apm-server.js (hunk 1 above)
Comment (vigneshshanmugam) [reply packages/rum-core/src/common/apm-server.js]: fixed as well.
