### PR TITLE
fix(rum): allow setting labels before initializing

### LINKED ISSUE #780: Refactor ConfigService to be able to set configs even before calling init
We can remove the `defaults` property and use its value to initialise `config` property on construction.

### PR DESCRIPTION
**Pull request by vigneshshanmugam**
+ fix #780 
+ User configs would be merged with the actual config instead of having `defaults`. 
+ Added a test case and removed the `config.init` from places where unnecessary.

### CODE REVIEW

**Comment by vigneshshanmugam** [comment]
@jahtalab Test failure is unrelated, Ready to be reviewed

File: packages/rum-core/src/common/config-service.js [hunk 1]
```diff
@@ -180,7 +179,7 @@ class Config {
       properties.serverUrl = properties.serverUrl.replace(/\/+$/, '')
     }
 
-    this.config = merge({}, this.defaults, this.config, properties)
+    this.config = merge({}, this.config, properties)
```
Comment (jahtalab) [inline packages/rum-core/src/common/config-service.js:182]: I don't think we still to pass a new object here, we can simply merge into `this.config`

File: packages/rum/test/specs/apm-base.spec.js [hunk 2]
```diff
@@ -308,6 +308,21 @@ describe('ApmBase', function() {
...
+    }
+    apmBase.addLabels(labels)
+    apmBase.init({
+      serviceName,
+      serverUrl,
+      disableInstrumentations: [PAGE_LOAD]
+    })
+    const configService = serviceFactory.getService('ConfigService')
+    expect(configService.get('context.tags')).toEqual(labels)
+  })
```
Comment (jahtalab) [inline packages/rum/test/specs/apm-base.spec.js:324]: I think having this test here is fine but since this change is in config service, the test should be in it's spec file. there can be two test if you think that's justified.

Comment (vigneshshanmugam) [reply packages/rum/test/specs/apm-base.spec.js:324]: There is already a test in config service, so I added this test to ensure setting labels before init.
